from pathlib import Path
from html import escape
root=Path(__file__).resolve().parents[1]
projects=[
 dict(slug='arki-pictures',name='Arki Pictures',number='01',category='Brand, web & film',status='Ongoing',kind='arki',intro='A home for stories, on screen and beyond.',description='Brand identity, website design, and the work of bringing films to life.'),
 dict(slug='everyday-gourmet',name='Everyday Gourmet',number='02',category='UI/UX & visual identity',status='Academic project · 2025',kind='everyday',intro='Finding a little more joy in the everyday grocery run.',description='A local-food discovery concept for Cambridge, from identity to website and app.'),
 dict(slug='sous-chef',name='Web Sous-Chef',number='03',category='Interactive web & UI/UX',status='Academic project · 2025',kind='chef',intro='A playful little companion for the kitchen.',description='Recipes, a kitchen toolkit, and a robot with a few ideas for dinner.'),
 dict(slug='wrap-sheet',name='Wrap Sheet',number='04',category='Web tool & workflow design',status='In progress',kind='wrap',intro='Less time with receipts. More time for everything else.',description='An invoice-making tool exploring receipt scanning, AI, and mobile OCR.'),
 dict(slug='nan-studio',name='NAN / Clay practice',number='05',category='Ceramics',status='Ongoing practice',kind='clay',intro='Learning through clay, one object at a time.',description='An evolving ceramics practice. Making, repeating, and seeing what happens.'),
 dict(slug='handwritten-type',name='Handwritten type',number='06',category='Type experiment',status='Personal experiment',kind='type',intro='A small experiment in making my handwriting into type.',description='A personal handwritten font, made from the marks I already make.')
]
def art(p):
 k=p['kind']
 if k=='arki': return '<div class="project-art arki-art"><img src="assets/arkiexample.jpeg" alt="A cinematic portrait washed in pink and green light"><span class="arki-wordmark" aria-hidden="true">arki pictures<small>Independent film & visual stories</small></span></div>'
 if k=='everyday': return '<div class="project-art everyday-art"><img src="assets/everyday-20.webp" alt="Everyday Gourmet website designs with orange and green identity and illustrated produce" loading="lazy"></div>'
 if k=='chef': return '<div class="project-art chef-art"><span class="chef-title" aria-hidden="true">web sous-chef</span><img src="assets/sous-chef-robot.svg" alt="The illustrated Sous-Chef robot"><span class="mono" aria-hidden="true">a little help in the kitchen.</span></div>'
 if k=='wrap': return '<div class="project-art wrap-art"><div class="invoice-cover" aria-hidden="true"><span class="mono">A TOOL IN THE MAKING</span><strong>wrap<br>sheet.</strong><div><div class="invoice-rule">01 / Collect receipts</div><div class="invoice-rule">02 / Review the details</div><div class="invoice-rule">03 / Make an invoice</div></div><span class="invoice-bottom">RECEIPTS → SOMETHING ORGANIZED</span></div></div>'
 if k=='clay':return '<div class="project-art"><img src="assets/nanexample.jpeg" alt="A collection of pale ceramic bowls inside a kiln" loading="lazy"></div>'
 return '<div class="project-art type-art"><span class="eyebrow">A note from the lab</span><strong>From hand<br>to keyboard.</strong><p>A personal font experiment.<br>Specimen to come.</p></div>'
def nav(active):
 return '<a class="skip" href="#main">Skip to content</a><header class="wrap"><nav class="site-nav" aria-label="Main navigation"><a class="brand" href="index.html" aria-label="Marina Mingnan Xu — home"><img src="assets/nanlogo.png" alt=""><span>marina<br>mingnan xu</span></a><div class="nav-links">'+''.join(f'<a href="{href}"'+(' aria-current="page"' if active==label else '')+f'>{label}</a>' for label,href in [('Index','index.html'),('Lab','lab.html'),('About','about.html')])+'<a href="#contact">Contact</a></div></nav></header>'
def footer():
 return '<footer class="site-footer wrap" id="contact"><div class="footer-top"><div><span class="eyebrow">Always open to a conversation</span><h2>Say hello.</h2><a class="text-link" href="mailto:marinaxu99@gmail.com">marinaxu99@gmail.com <span aria-hidden="true">↗</span></a></div><div class="footer-links"><a href="https://www.instagram.com/marina_xu99/" target="_blank" rel="noopener noreferrer">Instagram ↗</a><a href="https://www.linkedin.com/in/marina-mingnan-xu" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="#top">Back to top ↑</a></div></div><div class="footer-bottom"><span>© 2026 Marina Mingnan Xu</span><span>An ongoing collection. Designed & built by Marina.</span></div></footer>'
def page(file,title,body,active='',description='A personal archive of design, film, web experiments, and ceramics by Marina Mingnan Xu.'):
 root.joinpath(file).write_text('<!doctype html>\n<html lang="en" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'+escape(title)+' — Marina Mingnan Xu</title><meta name="description" content="'+escape(description,quote=True)+'"><meta name="theme-color" content="#faf9f6"><link rel="icon" type="image/png" href="assets/nanlogo.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="stylesheet" href="css/styles.css"></head><body>'+nav(active)+'<main id="main" class="wrap">'+body+'</main>'+footer()+'</body></html>\n')
def card(p):
 return f'<a class="project-card" href="{p["slug"]}.html">'+art(p)+f'<div class="card-info"><div><h3 class="card-title"><span class="project-number">{p["number"]}</span>{p["name"]}</h3><p>{p["category"]}</p></div><span class="mono" aria-hidden="true">↗</span></div></a>'
def rows():
 return ''.join(f'<a class="archive-row" href="{p["slug"]}.html"><span class="mono muted">{p["number"]}</span><span class="title">{p["name"]}</span><span class="meta">{p["category"]}</span><span class="meta status">{p["status"]}</span><span class="arrow" aria-hidden="true">↗</span></a>' for p in projects)
page('index.html','Index','''<section class="hero"><div class="hero-top"><span class="eyebrow">Marina Mingnan Xu / Personal archive</span><span class="mono location">SUZHOU ↔ SEOUL</span></div><h1>I mostly design.<br>Sometimes <em>other things.</em></h1><div class="hero-bottom"><p>Websites, films, useful little tools, and things made by hand. A collection of what I do, and what I’m figuring out.</p><a class="text-link" href="#archive">Browse the archive <span aria-hidden="true">↓</span></a></div></section><section aria-labelledby="selected-title"><div class="section-head"><h2 id="selected-title" class="eyebrow">Selected work</h2><span class="mono">01—04 / Selected</span></div><div class="project-grid">'''+''.join(card(p) for p in projects[:4])+'''</div></section><section class="archive" id="archive" aria-labelledby="archive-title"><div class="section-head"><h2 id="archive-title">The index</h2><span class="mono">All projects / 06</span></div>'''+rows()+'''</section><section class="lab-strip"><div class="lab-intro"><span class="eyebrow">Off the screen / In the lab</span><div><h2>A little room<br>to play.</h2><p>Clay, handwritten letters, and experiments without a brief. Some finished, some still taking shape.</p></div><a class="text-link" href="lab.html">Step into the lab <span aria-hidden="true">↗</span></a></div><a href="nan-studio.html" aria-label="Explore my clay practice"><img src="assets/nanexample.jpeg" alt="Ceramic bowls gathered inside a kiln" loading="lazy"></a></section>''','Index')
page('lab.html','Lab','''<header class="page-intro"><span class="eyebrow">Personal experiments / An open notebook</span><h1>Room to play.</h1><p>Things made out of curiosity. A place for small experiments, unfinished ideas, and learning by doing.</p></header><div class="lab-grid">'''+''.join(card(p) for p in projects[4:])+'''</div><section class="project-copy"><h2>A practice, in progress</h2><div><p>Some ideas become projects. Others stay small. I want to keep a place for both.</p><p>Right now, I’m practicing ceramics and exploring what happens when my handwriting becomes something I can type.</p></div></section>''','Lab')
page('about.html','About','''<header class="page-intro"><span class="eyebrow">A little about me</span><h1>Hi, I’m Marina.</h1><p>I design, make films, build things for the web, and sometimes throw clay.</p></header><section class="about-layout"><div><p>I like moving between different ways of making. A website gives me a way to organize an idea. A film brings people together around a story. Clay asks me to slow down and try again.</p><p>At Arki Pictures, I work across visual design and production. Alongside that, I explore digital experiences and small tools, and I’m building a ceramics practice one piece at a time.</p><p>This website is my personal archive: a place to gather what I’ve made, what I’m learning, and the projects I want to keep working on.</p><a class="text-link" href="index.html#archive">See what I’m making <span aria-hidden="true">↗</span></a></div><aside class="about-aside"><h2 class="eyebrow">Currently, in a few different forms</h2><div class="practice"><a href="arki-pictures.html">Arki Pictures ↗</a><p>Visual identity, web, and film production.</p></div><div class="practice"><a href="wrap-sheet.html">Tools & digital experiments ↗</a><p>UI/UX, websites, and ideas I can use.</p></div><div class="practice"><a href="nan-studio.html">NAN / Clay practice ↗</a><p>Learning to make things with my hands.</p></div></aside></section>''','About')
def copy(title,text):return f'<section class="project-copy"><h2>{title}</h2><div>{text}</div></section>'
def link(url,text):return f'<a class="text-link" href="{url}" target="_blank" rel="noopener noreferrer">{text} <span aria-hidden="true">↗</span></a>'
def gallery(items):return '<div class="gallery">'+''.join(f'<figure><a href="assets/{f}" target="_blank" rel="noopener noreferrer" aria-label="Open full-size: {escape(cap,quote=True)}"><img src="assets/{f}" alt="{escape(alt,quote=True)}" loading="lazy"></a><figcaption>{cap} · Open image ↗</figcaption></figure>' for f,cap,alt in items)+'</div>'
content={
'arki-pictures':copy('A shared creative home','<p>Arki Pictures is where my work in film and visual design comes together. I work on the identity and digital presence of the studio, alongside the coordination that helps a production move from an idea to a finished film.</p>')+copy('Between image and structure','<p>I’m interested in both what a project feels like and how it comes together: the visual language, the website, and the collaboration behind the scenes.</p><p>For me, Arki is an ongoing project. The brand and its home on the web grow alongside the work we make.</p>')+copy('Keep exploring',link('https://arkipictures.com','Visit Arki Pictures')),
'everyday-gourmet':copy('The starting point','<p>I began with an idea about local farm produce. Visiting grocery stores in Cambridge changed the direction: the handwritten signs, specialty goods, and conversations in the aisles were what made these places feel special.</p><p>Everyday Gourmet became a concept for helping young professionals and families discover that side of grocery shopping.</p>')+copy('One idea, two experiences','<p>The website is a place to discover stores, products, and their stories. The app explores a more everyday relationship: finding community posts, saving things of interest, and keeping up with local food culture.</p><p>I developed the identity alongside the interfaces, using warm orange and green, playful produce illustrations, and a mix of structured and handwritten typography.</p>')+gallery([('everyday-19.webp','01 / Website sketches & wireframes','Hand sketches and grayscale wireframes for four website pages'),('everyday-20.webp','02 / Website final designs','Everyday Gourmet homepage and About, Products, and Store layouts'),('everyday-22.webp','03 / App sketches & wireframes','App sketches and wireframes for splash, sign-in, community, and account'),('everyday-23.webp','04 / App final designs','Final mobile screens with orange and green accents')])+copy('What stayed with me','<p>Defining what each platform was for made the design process clearer. The visual details became easier to resolve once the content and purpose had a structure.</p><p class="note">An academic design concept for Design Strategy and Software II. These are design explorations and prototypes, rather than a launched grocery service.</p>')+copy('The full notebook',link('assets/everyday-gourmet-archive.pdf','Read the project archive (PDF)')),
'sous-chef':copy('A kitchen companion','<p>Web Sous-Chef is an interactive website I designed for Design & Interactive Experiences. It brings together a recipe generator, a mystery-recipe discovery flow, and small kitchen tools.</p><p>The robot, playful lettering, sounds, and little animations give practical tasks a lighter personality.</p>')+copy('Small interactions, useful outcomes','<p>The toolkit includes a cooking timer, temperature conversion, and volume conversion. The recipe flow starts with the ingredients you have; the mystery box introduces a little surprise through recipe videos.</p><p>I built the interface with HTML, CSS, and JavaScript, exploring API integration alongside the visual and interaction design.</p>')+copy('Still evolving','<p>The AI recipe connection needs another pass. I’m keeping this here as a record of the project, including the parts I want to improve.</p><p class="note">The live site is an experimental demo. AI recipe generation may be unavailable.</p>')+copy('Try the experiment',link('https://souschef.marinamingnanxu.com','Open Web Sous-Chef')),
'wrap-sheet':copy('An everyday admin problem','<p>Wrap Sheet is an invoice-making website I’m working on. The idea is to reduce the copying and organizing between a receipt and an invoice.</p><p>I’m exploring AI-assisted receipt scanning and phone-camera OCR, so receipt details can be reviewed and added to an invoice.</p>')+copy('The part I’m exploring','<p>How can a tool make the repetitive work easier while keeping the details easy to check? The flow I’m working toward is simple: collect a receipt, review the information, and bring it into the invoice.</p><p class="note">An active work in progress. The cover here is a project title graphic, not a screenshot of the current interface.</p>')+copy('Follow the work',link('https://marinaxu99.github.io/wrap-sheet/#invoice','Open Wrap Sheet')),
'nan-studio':copy('Beginning with the material','<p>NAN is the name I’m giving to an evolving ceramics practice. For now, I’m learning and making: working with clay, repeating forms, and paying attention to what changes from one attempt to the next.</p><p>I’m drawn to functional objects and the small signs of the hand that remain in them.</p>')+copy('A slower kind of making','<p>Alongside websites and film, clay gives me a different pace. The process is physical, and the result doesn’t always follow the plan. That’s part of why I want to keep doing it.</p><p class="note">A personal practice in progress. There is no collection for sale at the moment.</p>'),
'handwritten-type':copy('Keeping the personal marks','<p>I made a personal font from my handwriting using a handwriting-to-font tool. It’s a small experiment in taking something familiar and giving it a different life on screen.</p><p>I’m keeping a place for the experiment here as part of the lab.</p><p class="note">The font specimen is not on the site yet. The lettering on this page is the website’s regular typography.</p>')
}
for i,p in enumerate(projects):
 nxt=projects[(i+1)%len(projects)]
 body=f'<header class="project-header"><a class="back-link" href="index.html#archive">← Back to the index</a><h1>{p["name"]}</h1><p class="intro">{p["intro"]}</p><div class="project-meta"><div><span class="eyebrow muted">Practice</span><span>{p["category"]}</span></div><div><span class="eyebrow muted">Status</span><span>{p["status"]}</span></div><div><span class="eyebrow muted">Archive entry</span><span>{p["number"]} / 06</span></div></div></header><div class="project-hero">'+art(p)+'</div>'+content[p['slug']]+f'<div class="next-project"><span class="eyebrow">Next in the archive</span><a href="{nxt["slug"]}.html">{nxt["name"]} ↗</a></div>'
 page(p['slug']+'.html',p['name'],body,description=p['description'])
# Preserve old entry URLs as useful, complete pages instead of leaving broken routes.
root.joinpath('claystory.html').write_text(root.joinpath('nan-studio.html').read_text())
root.joinpath('gateway.html').write_text(root.joinpath('index.html').read_text())
root.joinpath('arki_main.html').write_text(root.joinpath('arki-pictures.html').read_text())
root.joinpath('404.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found — Marina Mingnan Xu</title><link rel="stylesheet" href="/css/styles.css"></head><body><main class="wrap page-intro"><p class="eyebrow">404 / Not in the archive</p><h1>A loose end.</h1><p>This page may have moved.</p><a class="text-link" href="/">Back to the index ↗</a></main></body></html>')
print('Built',len(list(root.glob('*.html'))),'static pages')
